 const locationData = [
            {
                name: "กทม. และภาคกลาง",
                id: "region-central",
                provinces: [
                    {
                        name: "จ.กรุงเทพมหานคร",
                        id: "province-bkk",
                        provinceCode: "10",
                        districts: [
                            { name: "อ.พระนคร", districtCode: "1" }, { name: "อ.ดุสิต", districtCode: "2" },
                            { name: "อ.หนองจอก", districtCode: "3" }, { name: "อ.บางรัก", districtCode: "4" },
                            { name: "อ.บางเขน", districtCode: "5" }, { name: "อ.บางกะปิ", districtCode: "6" },
                            { name: "อ.ปทุมวัน", districtCode: "7" }, { name: "อ.ป้อมปราบศัตรูพ่าย", districtCode: "8" },
                            { name: "อ.พระโขนง", districtCode: "9" }, { name: "อ.มีนบุรี", districtCode: "10" },
                            { name: "อ.ลาดกระบัง", districtCode: "11" }, { name: "อ.ยานนาวา", districtCode: "12" },
                            { name: "อ.สัมพันธวงศ์", districtCode: "13" }, { name: "อ.พญาไท", districtCode: "14" },
                            { name: "อ.ธนบุรี", districtCode: "15" }, { name: "อ.บางกอกใหญ่", districtCode: "16" },
                            { name: "อ.ห้วยขวาง", districtCode: "17" }, { name: "อ.คลองสาน", districtCode: "18" },
                            { name: "อ.ตลิ่งชัน", districtCode: "19" }, { name: "อ.บางกอกน้อย", districtCode: "20" },
                            { name: "อ.บางขุนเทียน", districtCode: "21" }, { name: "อ.ภาษีเจริญ", districtCode: "22" },
                            { name: "อ.หนองแขม", districtCode: "23" }, { name: "อ.ราษฎร์บูรณะ", districtCode: "24" },
                            { name: "อ.บางพลัด", districtCode: "25" }, { name: "อ.ดินแดง", districtCode: "26" },
                            { name: "อ.บึงกุ่ม", districtCode: "27" }, { name: "อ.สาทร", districtCode: "28" },
                            { name: "อ.บางซื่อ", districtCode: "29" }, { name: "อ.จตุจักร", districtCode: "30" },
                            { name: "อ.บางคอแหลม", districtCode: "31" }, { name: "อ.ประเวศ", districtCode: "32" },
                            { name: "อ.คลองเตย", districtCode: "33" }, { name: "อ.สวนหลวง", districtCode: "34" },
                            { name: "อ.จอมทอง", districtCode: "35" }, { name: "อ.ดอนเมือง", districtCode: "36" },
                            { name: "อ.ราชเทวี", districtCode: "37" }, { name: "อ.ลาดพร้าว", districtCode: "38" },
                            { name: "อ.วัฒนา", districtCode: "39" }, { name: "อ.บางแค", districtCode: "40" },
                            { name: "อ.หลักสี่", districtCode: "41" }, { name: "อ.สายไหม", districtCode: "42" },
                            { name: "อ.คันนายาว", districtCode: "43" }, { name: "อ.สะพานสูง", districtCode: "44" },
                            { name: "อ.วังทองหลาง", districtCode: "45" }, { name: "อ.คลองสามวา", districtCode: "46" },
                            { name: "อ.บางนา", districtCode: "47" }, { name: "อ.ทวีวัฒนา", districtCode: "48" },
                            { name: "อ.ทุ่งครุ", districtCode: "49" }, { name: "อ.บางบอน", districtCode: "50" }
                        ]
                    },
                    { name: "จ.สมุทรปราการ", id: "province-samutprakan", provinceCode: "11", districts: [] },
                    { name: "จ.นนทบุรี", id: "province-nonthaburi", provinceCode: "12", districts: [] },
                    { name: "จ.ปทุมธานี", id: "province-pathumthani", provinceCode: "13", districts: [] },
                    { name: "จ.พระนครศรีอยุธยา", id: "province-ayutthaya", provinceCode: "14", districts: [] },
                    { name: "จ.อ่างทอง", id: "province-angthong", provinceCode: "15", districts: [] },
                    { name: "จ.ลพบุรี", id: "province-lopburi", provinceCode: "16", districts: [] },
                    { name: "จ.สิงห์บุรี", id: "province-singburi", provinceCode: "17", districts: [] },
                    { name: "จ.ชัยนาท", id: "province-chainat", provinceCode: "18", districts: [] },
                    { name: "จ.สระบุรี", id: "province-saraburi", provinceCode: "19", districts: [] },
                    { name: "จ.นครนายก", id: "province-nakhonnayok", provinceCode: "26", districts: [] },
                    { name: "จ.นครสวรรค์", id: "province-nakhonsawan", provinceCode: "60", districts: [] },
                    { name: "จ.อุทัยธานี", id: "province-uthaithani", provinceCode: "61", districts: [] },
                    { name: "จ.กำแพงเพชร", id: "province-kamphaengphet", provinceCode: "62", districts: [] },
                    { name: "จ.สุโขทัย", id: "province-sukhothai", provinceCode: "64", districts: [] },
                    { name: "จ.พิษณุโลก", id: "province-phitsanulok", provinceCode: "65", districts: [] },
                    { name: "จ.พิจิตร", id: "province-phichit", provinceCode: "66", districts: [] },
                    { name: "จ.เพชรบูรณ์", id: "province-phetchabun", provinceCode: "67", districts: [] },
                    { name: "จ.สุพรรณบุรี", id: "province-suphanburi", provinceCode: "72", districts: [] },
                    { name: "จ.นครปฐม", id: "province-nakhonpathom", provinceCode: "73", districts: [] },
                    { name: "จ.สมุทรสาคร", id: "province-samutsakhon", provinceCode: "74", districts: [] },
                    { name: "จ.สมุทรสงคราม", id: "province-samutsongkhram", provinceCode: "75", districts: [] }
                ]
            },
            { name: "ภาคเหนือ", id: "region-north", provinces: [] },
            { name: "ภาคตะวันออกเฉียงเหนือ", id: "region-northeast", provinces: [] },
            { name: "ภาคตะวันออก", id: "region-east", provinces: [] },
            { name: "ภาคตะวันตก", id: "region-west", provinces: [] },
            { name: "ภาคใต้", id: "region-south", provinces: [] }
        ];