 const locationData = [
            {
                name: "กทม. และภาคกลาง",
                id: "region-central",
                provinces: [
                    {
                        name: "กรุงเทพมหานคร",
                        id: "province-bkk",
                        provinceCode: "10",
                        districts: [
                            { name: "พระนคร", districtCode: "1" }, { name: "ดุสิต", districtCode: "2" },
                            { name: "หนองจอก", districtCode: "3" }, { name: "บางรัก", districtCode: "4" },
                            { name: "บางเขน", districtCode: "5" }, { name: "บางกะปิ", districtCode: "6" },
                            { name: "ปทุมวัน", districtCode: "7" }, { name: "ป้อมปราบศัตรูพ่าย", districtCode: "8" },
                            { name: "พระโขนง", districtCode: "9" }, { name: "มีนบุรี", districtCode: "10" },
                            { name: "ลาดกระบัง", districtCode: "11" }, { name: "ยานนาวา", districtCode: "12" },
                            { name: "สัมพันธวงศ์", districtCode: "13" }, { name: "พญาไท", districtCode: "14" },
                            { name: "ธนบุรี", districtCode: "15" }, { name: "บางกอกใหญ่", districtCode: "16" },
                            { name: "ห้วยขวาง", districtCode: "17" }, { name: "คลองสาน", districtCode: "18" },
                            { name: "ตลิ่งชัน", districtCode: "19" }, { name: "บางกอกน้อย", districtCode: "20" },
                            { name: "บางขุนเทียน", districtCode: "21" }, { name: "ภาษีเจริญ", districtCode: "22" },
                            { name: "หนองแขม", districtCode: "23" }, { name: "ราษฎร์บูรณะ", districtCode: "24" },
                            { name: "บางพลัด", districtCode: "25" }, { name: "ดินแดง", districtCode: "26" },
                            { name: "บึงกุ่ม", districtCode: "27" }, { name: "สาทร", districtCode: "28" },
                            { name: "บางซื่อ", districtCode: "29" }, { name: "จตุจักร", districtCode: "30" },
                            { name: "บางคอแหลม", districtCode: "31" }, { name: "ประเวศ", districtCode: "32" },
                            { name: "คลองเตย", districtCode: "33" }, { name: "สวนหลวง", districtCode: "34" },
                            { name: "จอมทอง", districtCode: "35" }, { name: "ดอนเมือง", districtCode: "36" },
                            { name: "ราชเทวี", districtCode: "37" }, { name: "ลาดพร้าว", districtCode: "38" },
                            { name: "วัฒนา", districtCode: "39" }, { name: "บางแค", districtCode: "40" },
                            { name: "หลักสี่", districtCode: "41" }, { name: "สายไหม", districtCode: "42" },
                            { name: "คันนายาว", districtCode: "43" }, { name: "สะพานสูง", districtCode: "44" },
                            { name: "วังทองหลาง", districtCode: "45" }, { name: "คลองสามวา", districtCode: "46" },
                            { name: "บางนา", districtCode: "47" }, { name: "ทวีวัฒนา", districtCode: "48" },
                            { name: "ทุ่งครุ", districtCode: "49" }, { name: "บางบอน", districtCode: "50" }
                        ]
                    },
                    { name: "สมุทรปราการ", id: "province-samutprakan", provinceCode: "11", districts: [] },
                    { name: "นนทบุรี", id: "province-nonthaburi", provinceCode: "12", districts: [] },
                    { name: "ปทุมธานี", id: "province-pathumthani", provinceCode: "13", districts: [] },
                    { name: "พระนครศรีอยุธยา", id: "province-ayutthaya", provinceCode: "14", districts: [] },
                    { name: "อ่างทอง", id: "province-angthong", provinceCode: "15", districts: [] },
                    { name: "ลพบุรี", id: "province-lopburi", provinceCode: "16", districts: [] },
                    { name: "สิงห์บุรี", id: "province-singburi", provinceCode: "17", districts: [] },
                    { name: "ชัยนาท", id: "province-chainat", provinceCode: "18", districts: [] },
                    { name: "สระบุรี", id: "province-saraburi", provinceCode: "19", districts: [] },
                    { name: "นครนายก", id: "province-nakhonnayok", provinceCode: "26", districts: [] },
                    { name: "นครสวรรค์", id: "province-nakhonsawan", provinceCode: "60", districts: [] },
                    { name: "อุทัยธานี", id: "province-uthaithani", provinceCode: "61", districts: [] },
                    { name: "กำแพงเพชร", id: "province-kamphaengphet", provinceCode: "62", districts: [] },
                    { name: "สุโขทัย", id: "province-sukhothai", provinceCode: "64", districts: [] },
                    { name: "พิษณุโลก", id: "province-phitsanulok", provinceCode: "65", districts: [] },
                    { name: "พิจิตร", id: "province-phichit", provinceCode: "66", districts: [] },
                    { name: "เพชรบูรณ์", id: "province-phetchabun", provinceCode: "67", districts: [] },
                    { name: "สุพรรณบุรี", id: "province-suphanburi", provinceCode: "72", districts: [] },
                    { name: "นครปฐม", id: "province-nakhonpathom", provinceCode: "73", districts: [] },
                    { name: "สมุทรสาคร", id: "province-samutsakhon", provinceCode: "74", districts: [] },
                    { name: "สมุทรสงคราม", id: "province-samutsongkhram", provinceCode: "75", districts: [] }
                ]
            },
            { name: "ภาคเหนือ", id: "region-north", provinces: [] },
            { name: "ภาคตะวันออกเฉียงเหนือ", id: "region-northeast", provinces: [] },
            { name: "ภาคตะวันออก", id: "region-east", provinces: [] },
            { name: "ภาคตะวันตก", id: "region-west", provinces: [] },
            { name: "ภาคใต้", id: "region-south", provinces: [] }
        ];